apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: categorisation-tool
  labels:
    app: categorisation-tool
spec:
  replicas: 2
  revisionHistoryLimit: 2
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: categorisation-tool
  template:
    metadata:
      labels:
        app: categorisation-tool
    spec:
      containers:
        - name: categorisation-tool
          image: 926803513772.dkr.ecr.eu-west-1.amazonaws.com/omic/categorisation-tool:latest
          imagePullPolicy: IfNotPresent
          # command: ['sh', '-c', "bundle exec puma -p 3000 -C ./config/puma_prod.rb --pidfile /tmp/server.pid"]
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 360m
              memory: "1024Mi"
            requests:
              cpu: 180m
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            periodSeconds: 30
            timeoutSeconds: 5
          env:
            - name: NOMIS_OAUTH_PUBLIC_KEY
              value: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFqVGR1dEtLZVBSQmVBY2tnUzZwLwpsVitkNVlxYjNxMTh6NlV3aDFNTll4cDNIcVlwWVYrOTJ5RnhlMlE1UjdLVmpJeUt5MmZHQWpzV3krZVNOMjNUCkZURVVUeXdHdnc0SkJrRGRoaUUvKy80SjR2TWFHMzBYN29GdE9JUWIwaENFQVlWM3o4emc1WVd2OGZlRkVnWGcKSndKNUJzaStTQ29qM0hkOURFeTVkZlpNOWMvcGg5c3lhaktTVmJBbytEK1dqeFBYdThSd1FKT0FTSDQ1RXByVAozSTMvTXZZcmNWb3ZDeFFWclFjcGMzYmNFNGx6WHRZUlcvcElqR1FaQSsvVmIzV2V2bkdRYmJ3UzR6enl5M2s4CkRCZ0pzQVJlVDI1eHp0ckptRGlZZXBHYkVKVHV0alRqR2NVOG1qUjRWZ3gwdHdqMk9DMzBES3dXbGlrMzhXTWwKTlFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t"
            - name: NOMIS_AUTH_URL
              value: "https://gateway.preprod.nomis-api.service.hmpps.dsd.io/auth"
            - name: ELITE2API_ENDPOINT_URL
              value: "https://gateway.preprod.nomis-api.service.hmpps.dsd.io/elite2api/"
            - name: CUSTODY_ENDPOINT_URL
              value: "https://gateway.preprod.nomis-api.service.hmpps.dsd.io/custodyapi/"
            - name: RISK_PROFILER_ENDPOINT_URL
              value: "http://offender-risk-profiler-svc:8080/"
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              valueFrom:
                secretKeyRef:
                  name: categorisation-tool-secrets
                  key: application-insights-ikey
            - name: INGRESS_URL
              value: "https://categorisation-tool-preprod.apps.cloud-platform-live-0.k8s.integration.dsd.io"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: categorisation-tool-rds-preprod
                  key: database_password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: categorisation-tool-rds-preprod
                  key: database_username
            - name: DB_SERVER
              valueFrom:
                secretKeyRef:
                  name: categorisation-tool-rds-preprod
                  key: rds_instance_address
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: categorisation-tool-rds-preprod
                  key: database_name
            - name: API_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: categorisation-tool-secrets
                  key: api_client_id
            - name: API_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: categorisation-tool-secrets
                  key: api_client_secret
