module.exports = {
  '/categoriser(Home|Done)\\??(\\?.+)?': { authorised: ['ROLE_CREATE_CATEGORISATION'] },
  '/recategoriser(Home|HomeDevelopment|Done|Check)\\??(\\?.+)?': { authorised: ['ROLE_CREATE_RECATEGORISATION'] },
  '/recategoriserHome/hide-filter': { authorised: ['ROLE_CREATE_RECATEGORISATION'] },
  '/categoriserHome/hide-filter': { authorised: ['ROLE_CREATE_CATEGORISATION'] },
  '/riskProfileChangeDetail/\\d+': { authorised: ['ROLE_CREATE_RECATEGORISATION'] },
  '/supervisor(Home|Done)': { authorised: ['ROLE_APPROVE_CATEGORISATION'] },
  '/security(Home|Done|Upcoming)': { authorised: ['ROLE_CATEGORISATION_SECURITY'] },
  '/dashboard(Initial|Recat)(\\?.+)?': { authorised: ['ROLE_APPROVE_CATEGORISATION'] },
  '/categoryHistory/\\d+': { authorised: ['BOOKING_ID_IN_CASELOAD'] },
  '/tasklist/\\d+(\\?.+)?': { authorised: ['ROLE_CREATE_CATEGORISATION'] },
  '/tasklist/supervisor/(outcome/)?\\d+.+': { authorised: ['ROLE_APPROVE_CATEGORISATION'] },
  '/tasklist/categoriserSubmitted/\\d+': { authorised: ['ROLE_CREATE_CATEGORISATION'] },
  '/tasklistRecat/\\d+(\\?.+)?': { authorised: ['ROLE_CREATE_RECATEGORISATION'] },
  '/tasklistRecat/recategoriserSubmitted/\\d+?': { authorised: ['ROLE_CREATE_RECATEGORISATION'] },
  '/openConditionsAdded/\\d+(\\?.+)?': { authorised: ['ROLE_CREATE_CATEGORISATION', 'ROLE_CREATE_RECATEGORISATION'] },
  '/form/recat/.+': { authorised: ['ROLE_CREATE_RECATEGORISATION'] },
  '/form/ratings/.+': { authorised: ['ROLE_CREATE_CATEGORISATION'] },
  '/form/nextReviewDate/nextReviewDateStandalone.+': {
    authorised: ['ROLE_CREATE_CATEGORISATION', 'ROLE_CREATE_RECATEGORISATION', 'ROLE_APPROVE_CATEGORISATION'],
  },
  '/form/nextReviewDate/.+': { authorised: ['ROLE_CREATE_CATEGORISATION', 'ROLE_CREATE_RECATEGORISATION'] },
  '/form/openConditions/.+': {
    authorised: ['ROLE_CREATE_CATEGORISATION', 'ROLE_CREATE_RECATEGORISATION', 'ROLE_APPROVE_CATEGORISATION'],
  },
  '/form/categoriser/.+': { authorised: ['ROLE_CREATE_CATEGORISATION'] },
  '/form/supervisor/supervisorMessage/\\d+': {
    authorised: ['ROLE_CREATE_CATEGORISATION', 'ROLE_CREATE_RECATEGORISATION'],
  },
  '/form/supervisor/.+': { authorised: ['ROLE_APPROVE_CATEGORISATION'] },
  '/form/security/.+': { authorised: ['ROLE_CATEGORISATION_SECURITY'] },
  '/form/approvedView/\\d+(\\?.+)?': { authorised: ['BOOKING_ID_IN_CASELOAD'] },
  '/form/awaitingApprovalView/\\d+': { authorised: ['ROLE_CREATE_CATEGORISATION', 'ROLE_CREATE_RECATEGORISATION'] },
  '/form/cancel(Confirmed)?/\\d+': { authorised: ['ROLE_CREATE_CATEGORISATION', 'ROLE_CREATE_RECATEGORISATION'] },
  '/\\d+': { authorised: ['BOOKING_ID_IN_CASELOAD'] },
  '/categoriserLanding/\\d+': { authorised: ['ROLE_CREATE_CATEGORISATION'] },
  '/supervisorLanding/\\d+': { authorised: ['ROLE_APPROVE_CATEGORISATION'] },
  '/securityLanding/\\d+': { authorised: ['ROLE_CATEGORISATION_SECURITY'] },
  '/securityLanding/cancel/\\d+': { authorised: ['ROLE_CATEGORISATION_SECURITY'] },
  '/recategoriserLanding/\\d+': { authorised: ['ROLE_CREATE_RECATEGORISATION'] },
  '/landing/\\d+': { authorised: ['BOOKING_ID_IN_CASELOAD'] },
  '/switchRole/[A-Z_]+': {
    authorised: [
      'ROLE_CREATE_CATEGORISATION',
      'ROLE_CREATE_RECATEGORISATION',
      'ROLE_APPROVE_CATEGORISATION',
      'ROLE_CATEGORISATION_SECURITY',
    ],
  },
  '/liteCategories/\\d+': { authorised: ['ROLE_CREATE_CATEGORISATION', 'ROLE_CREATE_RECATEGORISATION'] },
  '/liteCategories/(approve/\\d+|approveList)': { authorised: ['ROLE_APPROVE_CATEGORISATION'] },
  '/liteCategories/confirmed/\\d+': {
    authorised: ['ROLE_CREATE_CATEGORISATION', 'ROLE_CREATE_RECATEGORISATION', 'ROLE_APPROVE_CATEGORISATION'],
  },
  '/liteCategories/alreadyApproved/\\d+': {
    authorised: ['ROLE_APPROVE_CATEGORISATION'],
  },
}
