export const ROLE = {
  ROLE_APPROVE_CATEGORISATION: 'ROLE_APPROVE_CATEGORISATION',
  ROLE_CATEGORISATION_SECURITY: 'ROLE_CATEGORISATION_SECURITY',
  ROLE_CREATE_CATEGORISATION: 'ROLE_CREATE_CATEGORISATION',
  ROLE_CREATE_RECATEGORISATION: 'ROLE_CREATE_RECATEGORISATION',
}
