apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dead-letter
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/version: "{{ with index .Values "generic-service" }}{{ .image.tag }}{{ end }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: offender-categorisation
    app.kubernetes.io/instance: offender-categorisation
spec:
  schedule: "11 */6 * * *"
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 1200
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ with index .Values "generic-service" }}{{ .serviceAccountName }}{{ end }}
          containers:
          - name: offender-categorisation
            image: "{{ with index .Values "generic-service" }}{{ .image.repository }}:{{ .image.tag }}{{ end }}"
            args:
            - node
            - jobs/dead-letter/clearDeadLetterQueuesWithExit
{{- include "deployment.envs" (index .Values "generic-service") | nindent 12 }}
          restartPolicy: Never
          activeDeadlineSeconds: 1200
