apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: categorisation-tool
  labels:
    app: categorisation-tool
spec:
  replicas: 2
  revisionHistoryLimit: 2
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: categorisation-tool
  template:
    metadata:
      labels:
        app: categorisation-tool
    spec:
      containers:
        - name: categorisation-tool
          image: 926803513772.dkr.ecr.eu-west-1.amazonaws.com/omic/categorisation-tool:latest
          imagePullPolicy: IfNotPresent
          # command: ['sh', '-c', "bundle exec puma -p 3000 -C ./config/puma_prod.rb --pidfile /tmp/server.pid"]
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 360m
              memory: "1024Mi"
            requests:
              cpu: 180m
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            periodSeconds: 30
            timeoutSeconds: 5
          env:
            - name: NOMIS_OAUTH_PUBLIC_KEY
              value: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFwSkdtYWp6SW9POVdSY2owM2VTbQpFeWJTYnNJaEdkNkRWVDRxUWFSRTZwN3RIN1ppSklvRWtzczRkOFphMGhuYWJwa0JqWTYwS3NnMW5teXpoZVlSCithWXVtc0gxbm1JcmJ4ZCtqV043T3A2V1pteWRBU3JMek1XWVdBYlNHOHBXMXkxY1RwdkRaMTlBSGJTYTRRL2UKSnRlcDFscCsyMnVHMW5kTVRwclRkNjRLTkcyZnRwcmV3aFExeE5xdmtUWjZoQnVRRVJKMzFhUXBkRThNQTFxSwpDWnI3VDJxTk1BTWNkTlpia0FqRjVLOXE0alZ0QkY3WXFPeXJ0T1JmTldqYUJoWHA5TlN0YWJCTXBURTdQNm8vClhJaU9rcmltNjlzaG1OdDhVRlU3WUlJN0ZvejgzM29HZnk2dmtDRjRxcGpIZ0RNc21STjc1UXRrRmRtaU8xaDgKcHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t"
            - name: NOMIS_AUTH_URL
              value: "https://gateway.prod.nomis-api.service.hmpps.dsd.io/auth"
            - name: ELITE2API_ENDPOINT_URL
              value: "https://gateway.prod.nomis-api.service.hmpps.dsd.io/elite2api/"
            - name: RISK_PROFILER_ENDPOINT_URL
              value: "http://offender-risk-profiler-svc:8080/"
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              valueFrom:
                secretKeyRef:
                  name: categorisation-tool-secrets
                  key: application-insights-ikey
            - name: INGRESS_URL
              value: "https://categorisation-tool.apps.cloud-platform-live-0.k8s.integration.dsd.io"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: categorisation-tool-rds-production
                  key: database_password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: categorisation-tool-rds-production
                  key: database_username
            - name: DB_SERVER
              valueFrom:
                secretKeyRef:
                  name: categorisation-tool-rds-production
                  key: rds_instance_address
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: categorisation-tool-rds-production
                  key: database_name
            - name: API_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: categorisation-tool-secrets
                  key: api_client_id
            - name: API_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: categorisation-tool-secrets
                  key: api_client_secret
            - name: GOOGLE_ANALYTICS_ID
              value: "GTM-MVD7G3F"
