---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: pp.offender-categorisation.service.justice.gov.uk
  namespace: offender-categorisation-preprod
spec:
  secretName: offender-categorisation-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'preprod.offender-categorisation.service.justice.gov.uk'
  acme:
    config:
    - domains:
      - 'preprod.offender-categorisation.service.justice.gov.uk'
      dns01:
        provider: route53-cloud-platform
