generic-service:
  replicaCount: 2

  image:
    repository: ghcr.io/ministryofjustice/offender-categorisation
    tag: latest
    pullPolicy: IfNotPresent
    port: 3000

  ingress:
    enable_allowlist: true
    hosts: [dev.offender-categorisation.service.justice.gov.uk]

  env:
    ENVIRONMENT: dev
    INGRESS_URL: https://dev.offender-categorisation.service.justice.gov.uk
    NOMIS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    ELITE2API_ENDPOINT_URL: https://prison-api-dev.prison.service.justice.gov.uk/
    RISK_PROFILER_ENDPOINT_URL: http://offender-risk-profiler/
    ALLOCATION_MANAGER_ENDPOINT_URL: https://dev.moic.service.justice.gov.uk/
    PRISONER_SEARCH_ENDPOINT_URL: https://prisoner-search-dev.prison.service.justice.gov.uk/
    RISKS_AND_NEEDS_ENDPOINT_URL: https://assess-risks-and-needs-dev.hmpps.service.justice.gov.uk/
    PROBATION_OFFENDER_SEARCH_ENDPOINT_URL: https://probation-offender-search-dev.hmpps.service.justice.gov.uk/
    OFFENDER_CATEGORISATION_API_ENDPOINT_URL: https://hmpps-offender-categorisation-api-dev.hmpps.service.justice.gov.uk/
    PATHFINDER_API_ENDPOINT_URL: https://dev-api.pathfinder.service.justice.gov.uk/
    ALERTS_ENDPOINT_URL: https://alerts-api-dev.hmpps.service.justice.gov.uk/
    ADJUDICATIONS_ENDPOINT_URL: https://manage-adjudications-api-dev.hmpps.service.justice.gov.uk/
    DPS_URL: https://digital-dev.prison.service.justice.gov.uk/
    SUPPORT_URL: https://support-dev.hmpps.service.justice.gov.uk/
    COMPONENT_API_URL: https://frontend-components-dev.hmpps.service.justice.gov.uk

  allowlist:
    ark-nps-hmcts-ttp1: 195.59.75.0/24
    ark-nps-hmcts-ttp2: 194.33.192.0/25
    ark-nps-hmcts-ttp3: 194.33.193.0/25
    ark-nps-hmcts-ttp4: 194.33.196.0/25
    ark-nps-hmcts-ttp5: 194.33.197.0/25
    groups:
      - internal
      - prisons

# determine which slack channel alerts are sent to, via the correct Alert Manager receiver
generic-prometheus-alerts:
  alertSeverity: dps-sed-alerts-nonprod
