---
generic-service:

  replicaCount: 2

  image:
    repository: quay.io/hmpps/offender-categorisation
    tag: latest
    pullPolicy: IfNotPresent
    port: 3000

  ingress:
    host: dev.offender-categorisation.service.justice.gov.uk

  env:
    INGRESS_URL: https://dev.offender-categorisation.service.justice.gov.uk
    NOMIS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    ELITE2API_ENDPOINT_URL: https://api-dev.prison.service.justice.gov.uk/
    RISK_PROFILER_ENDPOINT_URL: http://offender-risk-profiler/
    ALLOCATION_MANAGER_ENDPOINT_URL: https://allocation-manager-staging.apps.live.cloud-platform.service.justice.gov.uk/
    DPS_URL: https://digital-dev.prison.service.justice.gov.uk/
