name: Integration tests

on:
  workflow_call:
    inputs:
      node_version_file:
        description: 'Passed to setup-node action to specify where to source the version of node from'
        required: false
        type: string
        default: '.nvmrc'

permissions:
  contents: read

jobs:
  integration_test:
    name: Run the cypress integration tests
    runs-on: ubuntu-latest
    env:
      RP_QUEUE_ACCESS_KEY_ID: dummy
      RP_QUEUE_SECRET_ACCESS_KEY: dummy
      RP_DL_QUEUE_ACCESS_KEY_ID: dummy
      RP_DL_QUEUE_SECRET_ACCESS_KEY: dummy
      EVENT_QUEUE_ACCESS_KEY_ID: dummy
      EVENT_QUEUE_SECRET_ACCESS_KEY: dummy
      EVENT_DL_QUEUE_ACCESS_KEY_ID: dummy
      EVENT_DL_QUEUE_SECRET_ACCESS_KEY: dummy
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_DEFAULT_REGION: eu-west-2
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      postgres:
        image: postgres:15.7
        env:
          POSTGRES_USER: form-builder
          POSTGRES_DB: form-builder
          POSTGRES_PASSWORD: form-builder
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d document-management"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      localstack:
        image: localstack/localstack:3.0.0
        env:
          SERVICES: sqs
          PERSISTENCE: /tmp/localstack/data
          TMP_DIR: /private
        ports:
          - 4566:4566
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ inputs.node_version_file }}
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ inputs.node_version_file }}
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: npm_build_artifacts
      - name: restore cache
        id: restore-cache
        uses: actions/cache/restore@v4
        env:
          cache-name: node-modules
        with:
          path: |
            ./node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Init testing framework if necessary
        run: npm run int-test-init:ci --if-present
      - name: Get wiremock
        shell: bash
        run: |
          curl -o wiremock.jar https://repo1.maven.org/maven2/org/wiremock/wiremock-standalone/3.9.1/wiremock-standalone-3.9.1.jar
      - name: Create localstack queues
        shell: bash
        run: |
          export AWS_PAGER=""
            aws --endpoint-url=http://localhost:4566 --region eu-west-2 sqs create-queue --queue-name event
            aws --endpoint-url=http://localhost:4566 --region eu-west-2 sqs create-queue --queue-name risk_profiler_change
            aws --endpoint-url=http://localhost:4566 --region eu-west-2 sqs create-queue --queue-name event_dlq
            aws --endpoint-url=http://localhost:4566 --region eu-west-2 sqs create-queue --queue-name risk_profiler_change_dlq
      - name: Prepare and run integration tests
        id: integration-tests
        shell: bash
        run: |
          nohup java -jar wiremock.jar --port 9091 &
          nohup npm run start-feature &
          sleep 5
          npm run int-test
      - name: upload results
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: npm_integration_test_artifacts
          path: |
            integration_tests/videos/
            integration_tests/screenshots/
            coverage/
            test_results/
            ctrf/
      - name: publish test report
        if: ${{ !cancelled() && github.event.repository.visibility == 'public' }}
        uses: dorny/test-reporter@v2
        with:
          artifact: npm_integration_test_artifacts
          name: Test Report
          path: 'test_results/**/*.xml'
          reporter: java-junit
          fail-on-empty: false
          fail-on-error: false
          list-suites: 'failed'
          list-tests: 'failed'
      - name: fail the action if the tests failed
        if: ${{ steps.integration-tests.outcome == 'failure' }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Integration tests failed')
